insert into Schedule.[ClassTypes](Name,CreatedDate,UpdatedDate) values ('BJJ Gi All Levels',GETDATE(),GETDATE())
insert into Schedule.[ClassTypes](Name,CreatedDate,UpdatedDate) values ('BJJ Gi Fundamenals',GETDATE(),GETDATE())
insert into Schedule.[ClassTypes](Name,CreatedDate,UpdatedDate) values ('BJJ No Gi All Levels',GETDATE(),GETDATE())
insert into Schedule.[ClassTypes](Name,CreatedDate,UpdatedDate) values ('BJJ Gi Biginners',GETDATE(),GETDATE())
insert into Schedule.[ClassTypes](Name,CreatedDate,UpdatedDate) values ('BJJ Advanced Class',GETDATE(),GETDATE())
insert into Schedule.[ClassTypes](Name,CreatedDate,UpdatedDate) values ('BJJ Competition Class',GETDATE(),GETDATE())

insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(1,6,45,7,45,1,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(1,18,30,19,30,4,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(1,19,30,20,30,5,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(2,18,30,19,30,2,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(2,19,30,20,30,6,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(3,18,30,19,30,4,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(3,19,30,20,30,1,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(4,18,30,19,30,1,GETDATE(),GETDATE())
insert into Schedule.TimeTables(DayofWeek,StartTimeHr,StartTimeMin,EndTimeHr,EndTimeMin,ClassTypeId,CreatedDate,UpdatedDate) values(4,19,30,20,30,3,GETDATE(),GETDATE())

insert into Student.Grades(Name,CreatedDate,UpdatedDate) values ('White',GETDATE(),GETDATE())
insert into Student.Grades(Name,CreatedDate,UpdatedDate) values ('Blue',GETDATE(),GETDATE())
insert into Student.Grades(Name,CreatedDate,UpdatedDate) values ('Purple',GETDATE(),GETDATE())
insert into Student.Grades(Name,CreatedDate,UpdatedDate) values ('Brown',GETDATE(),GETDATE())
insert into Student.Grades(Name,CreatedDate,UpdatedDate) values ('Black',GETDATE(),GETDATE())

insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Alex','Santos',5,4,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Tony','Wu',4,0,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Jeremy','Ong',4,0,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Tin','Nguyen',4,0,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Leonard','Correa',3,2,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Nick','La',3,3,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Gareth','Porter',3,0,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Kevin','Phuong',2,1,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Alex','Tasio',3,0,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Thushara','Amendra',4,0,GETDATE(),GETDATE())
insert into Student.people(FirstName,LastName,GradeId,Stripe,CreatedDate,UpdatedDate) values('Peppe','Impala',3,0,GETDATE(),GETDATE())

insert into DayAtDojo.Outcomes(Name,CreatedDate,UpdatedDate) values ('Win',GETDATE(),GETDATE())
insert into DayAtDojo.Outcomes(Name,CreatedDate,UpdatedDate) values ('Loose',GETDATE(),GETDATE())
insert into DayAtDojo.Outcomes(Name,CreatedDate,UpdatedDate) values ('Advantage',GETDATE(),GETDATE())
insert into DayAtDojo.Outcomes(Name,CreatedDate,UpdatedDate) values ('Disadvantage',GETDATE(),GETDATE())
insert into DayAtDojo.Outcomes(Name,CreatedDate,UpdatedDate) values ('Neutral',GETDATE(),GETDATE())

insert into DayAtDojo.Attendance(TimeTableId, AttendedOn,TechniqueOfTheDay,CreatedDate,UpdatedDate) values(1,GETDATE(),'Rear naked choke',GETDATE(),GETDATE())

insert into DayAtDojo.SparringDetails(AttendanceId,PersonId,OutcomeId,TechniqueUsed,CreatedDate,UpdatedDate) values(1,1,2,'Knee on belly',GETDATE(),GETDATE())
insert into DayAtDojo.SparringDetails(AttendanceId,PersonId,OutcomeId,TechniqueUsed,CreatedDate,UpdatedDate) values(1,1,2,'Passing the Guard',GETDATE(),GETDATE())
insert into DayAtDojo.SparringDetails(AttendanceId,PersonId,OutcomeId,TechniqueUsed,CreatedDate,UpdatedDate) values(1,1,2,'Arm bar from Guard',GETDATE(),GETDATE())