// <auto-generated />
using System;
using DayAtDojo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DayAtDojo.Data.Migrations
{
    [DbContext(typeof(DayAtDojoContext))]
    partial class DayAtDojoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DayAtDojo")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DayAtDojo.Domain.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AttendedOn");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("TechniqueOfTheDay");

                    b.Property<int>("TimeTableId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("DayAtDojo.Domain.Outcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("DayAtDojo.Domain.SparringDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttendanceId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("OutcomeId");

                    b.Property<int>("PersonId");

                    b.Property<string>("TechniqueUsed");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("OutcomeId");

                    b.ToTable("SparringDetails");
                });

            modelBuilder.Entity("DayAtDojo.Domain.SparringDetails", b =>
                {
                    b.HasOne("DayAtDojo.Domain.Attendance", "Attendance")
                        .WithMany("SparringDetails")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DayAtDojo.Domain.Outcome", "Outcome")
                        .WithMany("SparringDetails")
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
